config/routes.rb
Rails.application.routes.draw do
  resources :images
  resources :posts
  devise_for :users, controllers: {
    sessions: 'authentication/sessions',
    registrations: 'authentication/registrations'
  }

  authenticated :user do
    root 'main#dashboard', as: :authenticated_root
  end

  root "main#home"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
# == Schema Information
#
# Table name: images
#
#  id                      :integer          not null, primary key
#  title                   :string
#  description             :string
#  image_file_file_name    :string
#  image_file_content_type :string
#  image_file_file_size    :integer
#  image_file_updated_at   :datetime
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#  post_id                 :integer
#
# Indexes
#
#  index_images_on_post_id  (post_id)
#

class Image < ApplicationRecord
  belongs_to :post, optional: true
  has_attached_file :image_file, styles: { medium: "300x300>", thumb:"100x100>" }
  validates_attachment_content_type :image_file, content_type: /\Aimage\/.*\z/
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id               :integer          not null, primary key
#  html_content     :text
#  markdown_content :text             not null
#  user_id          :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#
# Indexes
#
#  index_posts_on_user_id  (user_id)
#

class Post < ApplicationRecord
  belongs_to :user
  validates :markdown_content, presence: true, length: { minimum: 2 }
  has_many :images
  after_save :update_images
  # after_create :push_to_web_sockets
  attr_accessor :image_ids

  def self.latest
    order("id desc")
  end


  private
    def update_images

      Image.where(post_id: nil).where(id: image_ids)
          .update_all(post_id: self.id)

      push_to_web_sockets

    end

    def push_to_web_sockets
      if created_at_changed?
        ActionCable.server.broadcast(
          "posts",
          data: json_view
        )
      end
    end

    def json_view
      ApplicationController.renderer.render(partial: "posts/post.json.jbuilder",locals:{post: self})
    end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :posts
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authentication/registrations_controller.rb
class Authentication::RegistrationsController < Devise::RegistrationsController
  respond_to :json
end

app/controllers/authentication/sessions_controller.rb
class Authentication::SessionsController < Devise::SessionsController
  respond_to :json
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:title, :description, :image_file)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def home
  end

  def dashboard
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.latest
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.new(post_params)
    @post.image_ids = params[:post][:image_ids]

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:html_content, :markdown_content, :user_id, :image_ids)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/images/_form.html.haml
= form_for @image do |f|
  - if @image.errors.any?
    #error_explanation
      %h2= "#{pluralize(@image.errors.count, "error")} prohibited this image from being saved:"
      %ul
        - @image.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :image_file
    = f.text_field :image_file
  .actions
    = f.submit 'Save'

app/views/images/edit.html.haml
%h1 Editing image

= render 'form'

= link_to 'Show', @image
\|
= link_to 'Back', images_path

app/views/images/index.html.haml
%h1 Listing images

%table
  %thead
    %tr
      %th Title
      %th Description
      %th Image file
      %th
      %th
      %th

  %tbody
    - @images.each do |image|
      %tr
        %td= image.title
        %td= image.description
        %td= image.image_file
        %td= link_to 'Show', image
        %td= link_to 'Edit', edit_image_path(image)
        %td= link_to 'Destroy', image, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Image', new_image_path

app/views/images/new.html.haml
%h1 New image

= render 'form'

= link_to 'Back', images_path

app/views/images/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @image.title
%p
  %b Description:
  = @image.description
%p
  %b Image file:
  = @image.image_file

= link_to 'Edit', edit_image_path(@image)
\|
= link_to 'Back', images_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FacilitoSocial</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.5.4/react-with-addons.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.5.4/react-dom.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,900" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flexboxgrid/6.3.1/flexboxgrid.min.css">
    <%= javascript_pack_tag "registration" %>
    <%= javascript_pack_tag "post_group" %>
  </head>

  <body>
    <%= render "partials/navigation" %>
    <%= yield %>
  </body>
</html>

app/views/main/dashboard.haml
.container
  = react_component('PostGroup')

app/views/main/home.haml
.full-page-height-vh.bg-color-blue-700.row.middle-xs.center-xs.color-white
  .col-xs-8.col-md-5.col-lg-4.text-left
    %h1 FacilitoSocial
    %p Red Social para desarrolladores
    .card.bg-color-white.padding
      = react_component("Registration")

app/views/partials/_navigation.haml
%nav.navbar.bg-color-pink-a200.main
  .container-fluid
    .navbar-header
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li= link_to "Inicio", root_path
        -if user_signed_in?
          %li=link_to "Cerrar sesión", destroy_user_session_path, method: :delete

app/views/posts/_form.html.haml
= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :html_content
    = f.text_area :html_content
  .field
    = f.label :markdown_content
    = f.text_area :markdown_content
  .field
    = f.label :user
    = f.text_field :user
  .actions
    = f.submit 'Save'

app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'

= link_to 'Show', @post
\|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
%h1 Listing posts

%table
  %thead
    %tr
      %th Html content
      %th Markdown content
      %th User
      %th
      %th
      %th

  %tbody
    - @posts.each do |post|
      %tr
        %td= post.html_content
        %td= post.markdown_content
        %td= post.user
        %td= link_to 'Show', post
        %td= link_to 'Edit', edit_post_path(post)
        %td= link_to 'Destroy', post, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Post', new_post_path

app/views/posts/new.html.haml
%h1 New post

= render 'form'

= link_to 'Back', posts_path

app/views/posts/show.html.haml
%p#notice= notice

%p
  %b Html content:
  = @post.html_content
%p
  %b Markdown content:
  = @post.markdown_content
%p
  %b User:
  = @post.user

= link_to 'Edit', edit_post_path(@post)
\|
= link_to 'Back', posts_path